services:
    app:
        container_name: moonlight-app-jar
        build:
            context: .
            dockerfile: App.Dockerfile
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            #the next three lines can be adjusted according to the end-users needs, in our case
            # we're using the production application.yml
            - SPRING_DATASOURCE_URL=jdbc:mysql://office.nasbg.com:33062/bootcamp_java_24_july
            - SPRING_DATASOURCE_USERNAME=bootcamp_java_24_july
            - SPRING_DATASOURCE_PASSWORD=eZ@8Pa21A56_2
        ports:
            - "8082:8080"
        volumes:
            - ./src/main/resources/application.yml:/app/config/application.yml
        networks:
            - bootcamp-app-network

    app-tests:
        container_name: moonlight-app-tests-jar
        build:
            context: .
            dockerfile: App.Dockerfile
        environment:
            - SPRING_PROFILES_ACTIVE=test
        volumes:
            - ./src/test/resources/application-test.yml:/app/config/application-test.yml
        networks:
            - bootcamp-app-network
        command: mvn clean test

networks:
    bootcamp-app-network:
        external: true
