server:
  port: 8090
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: bootcamp_java_24_july
  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp_java_24_july?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
stripe:
  stripe.secret-key: sk_test_51Q8S6909YXyOjhuaYH6ryNBr3UVFGvOrGHiYhozPedFPAkiuDrUMdfEi7f7xOmgdxt6HHNdPXLLPSDnL7QnMMfzO00IQbJCZAi
  stripe.publishable-key: pk_test_51Q8S6909YXyOjhuaUTgDOByaAFFQEN1FiXVttn1BOsiD4G51xeMXiWsGZWDJCKDdYgEOuzVw54j3cH6pARjoMrm600u5JElaFW
  stripe.webhook-secret: whsec_9004f866b04260d293e6a0adf1e936d4d47a1ae78d89482ef2bdc3eb629fad69


