spring:
    profiles:
        active: dev
    server:
        error:
        include-message: always
        include-binding-errors: always
    datasource:
        url: jdbc:mysql://office.nasbg.com:33062/bootcamp_java_24_july
        username: bootcamp_java_24_july
        password: eZ@8Pa21A56_2
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

    mail:
        host: mail.nasbg.com
        port: 465
        username: "bootcamp@nasbg.com"
        password: '%61%,g]AI,g_'
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000

server:
    port: 8080

web:
    access-url: https://office.nasbg.com/danni

spring-doc:
    api-docs:
        path: /api-docs

secret-key: 3236464233324341314236393235454146313246353844464642353838